version: '3'

services:
  transmission:
    container_name: transmission
    image: haugene/transmission-openvpn:latest
    privileged: true
    restart: always
    ports:
      - 9091:9091
    environment:
      - PUID=1000
      - PGID=1000
      - OPENVPN_PROVIDER=${VPN_PROVIDER}
      - OPENVPN_CONFIG=${VPN_CONFIG}
      - OPENVPN_USERNAME=${VPN_USERNAME}
      - OPENVPN_PASSWORD=${VPN_PASSWORD}
      - OPENVPN_OPTS=--inactive 3600 --ping 10 --ping-exit 60
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MOUNT_POINT}/transmission:/data

  radarr:
    container_name: radarr
    image: linuxserver/radarr:latest
    ports:
      - 7878:7878
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MOUNT_POINT}/radarr-config:/config
      - ${MOUNT_POINT}/transmission/completed:/downloads
      - ${MOUNT_POINT}/plex/movies:/movies
    depends_on:
      - transmission
  
  sonarr:
    container_name: sonarr
    image: linuxserver/sonarr:latest
    ports:
      - 8989:8989
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TIME_ZONE}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${MOUNT_POINT}/sonarr/config:/config
      - ${MOUNT_POINT}/transmission/completed:/downloads
      - ${MOUNT_POINT}/plex/tv:/tv
    depends_on:
      - transmission
